services:
  - type: web
    name: trangspecial
    env: php
    runtime: docker
    plan: free
    repo: https://github.com/ThuyTrang9525/MockAPI.git
    region: oregon
    envVars:
      - key: APP_ENV
        value: production
    buildCommand: "composer install && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
