export const data = [
  {
    id: 1,
    name: "Cold Brew Sữa Tươi",
    myfile: "https://static.kinhtedouong.vn/images/upload/huongtra/04012025/thiet-ke-katinat-saigon-kafe-17.jpg",
    type: "Cà Phê",
    price: 49000,
  },
  {
    id: 2,
    name: "Trà Oolong Sữa",
    myfile: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzkRGsJegKun_NoMuswnAjDVp9Z1pjBNOmPA&s",
    type: "Trà Sữa",
    price: 45000,
  },
  {
    id: 3,
    name: "Bánh Mousse Chocolate",
    myfile: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnaf_BwPWqgJAdnAYlVtNo2J7KahWXdZ8CfA&s",
    type: "Bánh Ngọt",
    price: 39000,
  },
  {
    id: 4,
    name: "Americano Đá",
    myfile: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyZI-Ev6c7rRP6dnVHu5evwe_fH7p5URMdYw&s",
    type: "Cà Phê",
    price: 39000,
  },
  {
    id: 5,
    name: "Trà Sữa Ô Long Nướng",
    myfile: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3_0d7BULjkxEjW4ohDJAfGukIOJ7HhcJ65w&s",
    type: "Trà Sữa",
    price: 49000,
  },
  {
    id: 6,
    name: "Bánh Phô Mai Nhật",
    myfile: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTcGUOfcjgb5TDZ7iYg67uJksHE690xAQ72A&s",
    type: "Bánh Ngọt",
    price: 45000,
  },
  {
    id: 7,
    name: "Cappuccino",
    myfile: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeGO9PnXjJPlzalurJi5_M4UI-8LCOqL_JnQ&s",
    type: "Cà Phê",
    price: 50000,
  },
  {
    id: 8,
    name: "Matcha Sữa Đá",
    myfile: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRvg2vm2ITVI2kGhf71hBpFiqpcqx8c_8ZbQ&s",
    type: "Trà Sữa",
    price: 55000,
  },
  {
    id: 9,
    name: "Bánh Tiramisu",
    myfile: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCiqXqjpXVjUXz41Fkbl1Q4I268TGuqmljuw&s",
    type: "Bánh Ngọt",
    price: 42000,
  },
  {
    id: 10,
    name: "Espresso Đơn",
    myfile: "https://katinat.vn/wp-content/uploads/2024/11/468425027_563256089736589_5408231295856571201_n.jpg",
    type: "Cà Phê",
    price: 35000,
  },
];
